In [1]:
import scanpy as sc
import pandas as pd
from scipy.sparse import csr_matrix

In [ ]:
print("1. Loading the massive matrix... (Your M4 will chew through this quickly)")
# The .T is critical! R stores data as (Genes x Cells). Python needs it as (Cells x Genes).
gli3_ko = sc.read_mtx("/Users/christianlangridge/Desktop/TabGRN/data/GLI3 KO validation/data_matrices/counts.mtx.gz").T 

# Convert to a Compressed Sparse Row (CSR) matrix. 
# This makes future operations (like UMAPs and filtering) lightning fast.
gli3_ko.X = csr_matrix(gli3_ko.X)

In [ ]:

print("2. Loading labels and metadata...")
# Use sep='\t' since we saved them as .tsv (tab-separated) in Kaggle
genes = pd.read_csv("/Users/christianlangridge/Desktop/SMT-Pipeline/data/GLI3 KO validation/data_matrices/features.tsv.gz", header=None, sep='\t')
barcodes = pd.read_csv("/Users/christianlangridge/Desktop/SMT-Pipeline/data/GLI3 KO validation/data_matrices/barcodes.tsv.gz", header=None, sep='\t')
metadata = pd.read_csv("/Users/christianlangridge/Desktop/SMT-Pipeline/data/GLI3 KO validation/data_matrices/meta.tsv.gz", index_col=0)

print("3. Stitching it all together...")
# Assign the labels to the AnnData object
gli3_ko.var_names = genes[0].values
gli3_ko.obs_names = barcodes[0].values
gli3_ko.obs = metadata

In [ ]:
### SAVING STICHED H5AD OBJECT 

print("4. Saving your Master File...")
# Save it as a compressed HDF5 file. This is your new gold standard.
gli3_ko.write("GLI3_ko_raw.h5ad", compression="gzip")

print("-" * 30)
print("✅ STITCHING COMPLETE!")
print(f"Total Cells: {gli3_ko.n_obs}")
print(f"Total Genes: {gli3_ko.n_vars}")
print("Your data is ready for analysis!")

In [ ]:
wls_ko = sc.read_h5ad("/Users/christianlangridge/Desktop/SMT-Pipeline/data/WLS KO validation/WLS_ko.h5ad")
print(wls_ko)

In [2]:
training_data_pseudotime = sc.read_h5ad("/Users/christianlangridge/Desktop/SMT-Pipeline/data/training_data/AnnData/neurectoderm_with_pseudotime.h5ad")
print(training_data_pseudotime)

AnnData object with n_obs × n_vars = 41059 × 24264
    obs: 'orig.ident', 'nCount_RNA', 'nFeature_RNA', 'dataset', 'percent.mt', 'S.Score', 'G2M.Score', 'Phase', 'old.ident', 'RNA_snn_res.1', 'seurat_clusters', 'RNA_snn_res.0.6', 'cluster.ids', 'class3', 'rank-transformed-pseudotime', 'raw_pseudotime'
    uns: 'log1p'

In [3]:
training_data_pseudotime.obs.head()

,orig.ident,nCount_RNA,nFeature_RNA,dataset,percent.mt,S.Score,G2M.Score,Phase,old.ident,RNA_snn_res.1,seurat_clusters,RNA_snn_res.0.6,cluster.ids,class3,rank-transformed-pseudotime,raw_pseudotime
HB4 D5_AAACCCACACCACTGG-1,HB4_D5,17669,5342,HB4 D5,8.814006,0.209518,-0.127892,S,S,12,1,1,1,Neurectoderm,0.151634,0.080734
HB4 D5_AAACCCATCAGACCGC-1,HB4_D5,11824,4479,HB4 D5,6.787574,0.161178,-0.146383,S,S,13,8,8,8,Neurectoderm,0.094000,0.053153
HB4 D5_AAACCCATCGGTCTGG-1,HB4_D5,15395,5178,HB4 D5,8.177034,0.012562,0.197323,G2M,G2M,7,1,1,1,Neurectoderm,0.183822,0.096048
HB4 D5_AAACGAACATCCCGTT-1,HB4_D5,8910,3862,HB4 D5,4.343957,0.001251,0.255539,G2M,G2M,13,7,7,7,Late Neurectoderm,0.328367,0.376261
HB4 D5_AAACGAAGTCGGTAAG-1,HB4_D5,14652,4856,HB4 D5,6.574299,0.220178,-0.128710,S,S,12,5,5,5,Neurectoderm,0.198373,0.103740

In [ ]:
gli3_ko = sc.read_h5ad("/Users/christianlangridge/Desktop/SMT-Pipeline/data/GLI3 KO validation/GLI3_ko.h5ad")
print(gli3_ko)

In [ ]:
gli3_ko_raw = sc.read_h5ad("/Users/christianlangridge/Desktop/SMT-Pipeline/data/GLI3 KO validation/GLI3_ko_raw.h5ad")
print(gli3_ko_raw)

In [ ]:
### EXTRACTING GLI3_KO_RAW FROM GLI3_KO


# 1. Check the main matrix (X)
# If these are integers (e.g., 0, 1, 5, 20), they are raw counts.
# If they are floats (e.g., 0.12, 1.5), they are normalized.
print(gli3_ko.X[:5, :5])

# 2. Check the 'raw' attribute (Most common for published data)
if gli3_ko.raw is not None:
    raw_counts = gli3_ko.raw.X
    print("Found raw counts in gli3_ko.raw")
else:
    print("No gli3_ko.raw found.")

# 3. Check for a 'counts' layer
if 'counts' in gli3_ko.layers:
    raw_counts = gli3_ko.layers['counts']
    print("Found raw counts in gli3_ko.layers['counts']")

In [2]:
training_data = sc.read_h5ad("/Users/christianlangridge/Desktop/SMT-Pipeline/data/training_data/AnnData/neurectoderm_complete.h5ad")
print(training_data)

AnnData object with n_obs × n_vars = 41059 × 24264
    obs: 'orig.ident', 'nCount_RNA', 'nFeature_RNA', 'dataset', 'percent.mt', 'S.Score', 'G2M.Score', 'Phase', 'old.ident', 'RNA_snn_res.1', 'seurat_clusters', 'RNA_snn_res.0.6', 'cluster.ids', 'class3'

In [3]:
training_data.obs.head()

,orig.ident,nCount_RNA,nFeature_RNA,dataset,percent.mt,S.Score,G2M.Score,Phase,old.ident,RNA_snn_res.1,seurat_clusters,RNA_snn_res.0.6,cluster.ids,class3
HB4 D5_AAACCCACACCACTGG-1,HB4_D5,17669,5342,HB4 D5,8.814006,0.209518,-0.127892,S,S,12,1,1,1,Neurectoderm
HB4 D5_AAACCCATCAGACCGC-1,HB4_D5,11824,4479,HB4 D5,6.787574,0.161178,-0.146383,S,S,13,8,8,8,Neurectoderm
HB4 D5_AAACCCATCGGTCTGG-1,HB4_D5,15395,5178,HB4 D5,8.177034,0.012562,0.197323,G2M,G2M,7,1,1,1,Neurectoderm
HB4 D5_AAACGAACATCCCGTT-1,HB4_D5,8910,3862,HB4 D5,4.343957,0.001251,0.255539,G2M,G2M,13,7,7,7,Late Neurectoderm
HB4 D5_AAACGAAGTCGGTAAG-1,HB4_D5,14652,4856,HB4 D5,6.574299,0.220178,-0.128710,S,S,12,5,5,5,Neurectoderm

In [14]:
# Get the object dimensions 
print(training_data.shape)

# Or access individually
print(f"Cells: {training_data.n_obs}")
print(f"Genes: {training_data.n_vars}")

# You can also directly access the matrix dimensions
print(training_data.X.shape)

(41059, 24264)
Cells: 41059
Genes: 24264
(41059, 24264)

In [6]:
cell_type = training_data.obs['class3'].unique()
print(cell_type)

['Neurectoderm', 'Late Neurectoderm', 'Unknown proliferating cells', 'Prosencephalic progenitors', 'Telencephalic progenitors', 'Late Prosencephalic progenitors', 'Diencephalic progenitors', 'Tel/Die neurons']
Categories (8, object): ['Diencephalic progenitors', 'Late Neurectoderm', 'Late Prosencephalic progenitors', 'Neurectoderm', 'Prosencephalic progenitors', 'Tel/Die neurons', 'Telencephalic progenitors', 'Unknown proliferating cells']

In [7]:
training_data.var.head()

Empty DataFrame
Columns: []
Index: [AL627309.1, AL627309.4, AL669831.2, AL669831.5, LINC00115]

In [11]:
days = training_data.obs['orig.ident'].unique()
print(days)

['HB4_D5', 'HB4_D7', 'HB4_D11', 'HB4_D16', 'HB4_D21', 'HB4_D30']
Categories (6, object): ['HB4_D5', 'HB4_D7', 'HB4_D11', 'HB4_D16', 'HB4_D21', 'HB4_D30']

In [10]:
counts = training_data.obs["class3"].value_counts()
for label, count in counts.items():
    print(f"{label}: {count}")

Neurectoderm: 10001
Telencephalic progenitors: 9681
Late Neurectoderm: 7962
Diencephalic progenitors: 4899
Late Prosencephalic progenitors: 4275
Tel/Die neurons: 1878
Prosencephalic progenitors: 1506
Unknown proliferating cells: 857

In [9]:
mask = (training_data.obs['orig.ident'] == 'HB4_D5') & (training_data.obs['class3'] == 'Diencephalic progenitors')
result = training_data.obs[mask]
print(result)

Empty DataFrame
Columns: [orig.ident, nCount_RNA, nFeature_RNA, dataset, percent.mt, S.Score, G2M.Score, Phase, old.ident, RNA_snn_res.1, seurat_clusters, RNA_snn_res.0.6, cluster.ids, class3]
Index: []

In [ ]:
wls_ko.obs.head()
unique_list2 = wls_ko.obs['anno_class1'].unique()
print(unique_list2)

In [ ]:
shared = set(unique_list) & set(unique_list2)  
print(shared)

In [ ]:
gli3_ko.obs.head()
unique_list3 = gli3_ko.obs['nowakowski_prediction'].unique()
print(unique_list3)

In [ ]:
gli3_ko_raw.obs.head()

In [ ]:
gli3_ko_raw = sc.read_h5ad("/Users/christianlangridge/Desktop/SMT-Pipeline/data/GLI3 KO validation/GLI3_ko_raw.h5ad")
print(gli3_ko_raw)

In [ ]:
# A quick standard pipeline to generate a UMAP in Python:
sc.pp.normalize_total(training_data, target_sum=1e4)
sc.pp.log1p(training_data)
sc.pp.highly_variable_genes(training_data, min_mean=0.0125, max_mean=3, min_disp=0.5)
sc.tl.pca(training_data, svd_solver='arpack')
sc.pp.neighbors(training_data, n_neighbors=10, n_pcs=40)
sc.tl.umap(training_data)

# Convert the cluster column from numbers to categories
training_data.obs['seurat_clusters'] = training_data.obs['seurat_clusters'].astype('category')

In [ ]:
# Now you can plot it using the metadata columns we saved!
sc.pl.umap(training_data, color=['class3', 'seurat_clusters'], wspace=0.5)

In [ ]:
print(gli3_ko.obs.columns.tolist())

In [ ]:
print(gli3_ko_raw.obs.columns.tolist())

In [ ]:
gli3_ko_raw.obs.head()

In [ ]:
training_data.obs.head()

In [ ]:
GLS_ko_AnnData.obs.head()

In [ ]:
# A quick standard pipeline to generate a UMAP in Python:
sc.pp.normalize_total(GLS_ko_AnnData, target_sum=1e4)
sc.pp.log1p(GLS_ko_AnnData)
sc.pp.highly_variable_genes(GLS_ko_AnnData, min_mean=0.0125, max_mean=3, min_disp=0.5)
sc.tl.pca(GLS_ko_AnnData, svd_solver='arpack')
sc.pp.neighbors(GLS_ko_AnnData, n_neighbors=10, n_pcs=40)
sc.tl.umap(GLS_ko_AnnData)

# Convert the cluster column from numbers to categories
GLS_ko_AnnData.obs['seurat_clusters'] = GLS_ko_AnnData.obs['seurat_clusters'].astype('category')

In [ ]:
# Now you can plot it using the metadata columns we saved!
sc.pl.umap(GLS_ko_AnnData, color=['class3', 'seurat_clusters'], wspace=0.5)

In [1]:
import scanpy as sc
adata = sc.read_h5ad("/Users/christianlangridge/Desktop/SMT-Pipeline/data/training_data/AnnData/neurectoderm_complete.h5ad")
print(adata.X.max())          # what's currently used
print(list(adata.layers))     # check for a log-norm layer

3479.0
[]